/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: "#f6f6fb",
        "on-error": "#ffefef",
        "surface-container": "#e7e8ee",
        "primary-fixed": "#9695ff",
        outline: "#75777b",
        "on-secondary-container": "#00468e",
        "primary-dim": "#3d38c5",
        "surface-dim": "#d2d4db",
        "outline-variant": "#acadb1",
        "secondary-fixed": "#bcd2ff",
        "primary-container": "#9695ff",
        error: "#b41340",
        tertiary: "#973773",
        "surface-variant": "#dbdde3",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#000000",
        "on-tertiary-fixed-variant": "#6c104f",
        "on-surface-variant": "#5a5b60",
        "on-primary": "#f4f1ff",
        "inverse-surface": "#0c0e12",
        primary: "#4a47d2",
        "on-secondary": "#eff2ff",
        "on-background": "#2d2f33",
        "tertiary-dim": "#882a67",
        "secondary-fixed-dim": "#a5c5ff",
        "secondary-container": "#bcd2ff",
        "tertiary-fixed-dim": "#ed7ebe",
        "error-container": "#f74b6d",
        "on-error-container": "#510017",
        "primary-fixed-dim": "#8686ff",
        "error-dim": "#a70138",
        "on-tertiary-fixed": "#350025",
        background: "#f6f6fb",
        "tertiary-container": "#fd8bcc",
        "inverse-primary": "#8382ff",
        "inverse-on-surface": "#9c9da1",
        "on-primary-container": "#10007f",
        "secondary-dim": "#004e9d",
        "surface-bright": "#f6f6fb",
        "on-secondary-fixed": "#00336b",
        "surface-container-low": "#f0f0f6",
        "surface-container-highest": "#dbdde3",
        "surface-container-high": "#e1e2e8",
        "tertiary-fixed": "#fd8bcc",
        "on-secondary-fixed-variant": "#004f9f",
        "surface-tint": "#4a47d2",
        "on-tertiary-container": "#610246",
        "on-tertiary": "#ffeff4",
        secondary: "#005ab2",
        "on-surface": "#2d2f33",
        "on-primary-fixed-variant": "#16009b"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
